### PR TITLE
add tests

### LINKED ISSUE #15: can't read libtool
Running `patch_libtool` did not work for me since it failed to find `libtool`, see [azure logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=411351&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=1909). Am I supposed to `cd` somewhere before running `patch_libtool`? If so, then this is not clear from the instructions here.

```
++ [[ win-64 == \w\i\n\-\6\4 ]]
++ patch_libtool
++ sed -i.bak s/export_symbols_cmds=/export_symbols_cmds2=/g libtool
sed: can't read libtool: No such file or directory
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Wanted to fix #15, found I had some uncommitted tests lying around. Let's try these first.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@isuruf
I managed to reproduce #15 with the tests here (c.f. https://github.com/conda-forge/autotools_clang_conda-feedstock/pull/16/commits/4d6ac64bd5c5ee299b206d94ac3e1842b701b335), but my first guess (making the paths explicit) didn't work out.

There's however some confusion (at least to me) with the various environments here - this feedstock is really only designed to be pulled in at `build:` time, but now I'm trying to shoehorn it into running at `test:` time. Perhaps you'd prefer a `downstream:` test-feedstock like for libcxx (sounds a bit overkill though for an internal tool)...?

**Comment by h-vetinari** [comment]
@isuruf
Would you be able to have a look here? Would be good if we could unbreak this piece of pretty important infrastructure.

**Comment by isuruf** [comment]
As the package name says, this is for building an autotools package and the test you are adding is not for an autotools package.

**Comment by h-vetinari** [comment]
> As the package name says, this is for building an autotools package and the test you are adding is not for an autotools package.

It's intended to be a minimal reproducer of #15, using the documented calls from the documentation in `meta.yaml`.

I don't really understand your point - I'm happy to adapt the tests however necessary (or indeed remove them) - but currently `patch_libtool` is not working

**Comment by isuruf** [comment]
I don't think you understand what a autotools project is. See https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html

**Comment by h-vetinari** [comment]
I do get the `configure` + `make` workflow, though - admittedly - not how it interacts with `patch_libtool` here. Are you saying that it's not an autotools projects without a call to `configure` before (note: the failure is the same regardless)?

The point is that the documentation of how to use this feedstock does not work even with the full monty of an autotools build, c.f.
```
# Not sure why this isn't working.
# [[ "$target_platform" == "win-64" ]] && patch_libtool
```
in https://github.com/conda-forge/ffmpeg-feedstock/pull/126 (https://github.com/hmaarrfk/ffmpeg-feedstock/commit/73461b1ec9bae4c7aeac28e0dae30a09fb22689b).

I don't know how important `patch_libtool` is in the grand scheme of things, but even though I don't understand all the intricacies, I'm trying to fix it.

**Comment by h-vetinari** [comment]
> but even though I don't understand all the intricacies, I'm trying to fix it.

It could be that the fix is documentation-only, but since it worked before, it seemed like there's more to it.

**Comment by isuruf** [comment]
> Are you saying that it's not an autotools projects without a call to configure before

Yes

> The point is that the documentation of how to use this feedstock does not work even with the full monty of an autotools build, c.f.

No, ffmpeg is not a full autotools project as it's not using libtool.

Please try a project using this package like `mpfr` and play around with it to get a feel of how it works.

**Comment by h-vetinari** [comment]
OK, closing this. I'm thinking the log message for calling `patch_libtool` only _after_ `configure` could be made an error in the function itself, but otherwise things should be fine.

**Pull request closed without merging**
